version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_VERSION=${APP_VERSION}
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
