apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: development
data:
  init.sql: |+
    CREATE DATABASE IF NOT EXISTS app_db;

    USE app_db;

    CREATE TABLE IF NOT EXISTS visitors (
        id INT AUTO_INCREMENT PRIMARY KEY,
        visit_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255),
        email VARCHAR(255)
    );

