apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytonh-app
  namespace: development
  labels:
    app: python-app
    env: dev
spec:
  selector:
    matchLabels:
      app: python-app
      env: dev
  template:
    metadata:
      labels:
        app: python-app
        env: dev
    spec:
      containers:
      - name: mysql-5.7
        image: mysql:5.7
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: pytonh-db-service
  namespace: development
  labels:
    app: python-app
    env: dev
spec:
  selector:
    app: python-app
    env: dev
  ports:
  - port: 3306
    targetPort: 3306
