apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-db-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-db
  template:
    metadata:
      labels:
        app: python-app-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "app_db"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc




---

apiVersion: v1
kind: Service
metadata:
  name: python-db-service   # Corrected typo in 'python'
  namespace: development
  labels:
    app: python-app
    env: dev
spec:
  selector:
    app: python-app
    env: dev
  ports:
  - name: mysql  # Add name for the port 
    port: 3306
    targetPort: 3306

