apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: puju3366/app:2.0
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "4.0"
        - name: MYSQL_HOST
          value: "mysql-service.development.svc.cluster.local"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: development
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

