name: Deploy to Kubernetes

on:
  push:
    branches: ["python"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_VERSION: "2.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: puju3366/app:${{ env.APP_VERSION }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'image'
          image-ref: puju3366/app:${{ env.APP_VERSION }}
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy-results.sarif

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: puju3366/app:${{ env.APP_VERSION }}


