name: Deploy to Kuberetes

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        run: echo "Hello There"
